// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufppusqbogkomuiszwfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmcHB1c3Fib2drb211aXN6d2ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzY0OTcsImV4cCI6MjA2NjAxMjQ5N30.1rlwgHtZ80x8l91rh1G2JU3SXKOu5r_gVa9kj5YB7iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);